{
 "title": "ASP.NET Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count, app)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Num threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_num_threads{app=~\"[[app]]\"})"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "stat",
   "description": "Amount of the virtual memory, in bytes, allocated for the associated process",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_virtual_memory_bytes{app=\"[[app]]\"})"
    }
   ]
  },
  {
   "title": "Working set",
   "type": "stat",
   "description": "Amount of physical memory, in bytes, allocated for the associated process",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_working_set_bytes{app=\"[[app]]\"})"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "description": "Approximation of the number of bytes currently allocated in managed memory",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(dotnet_total_memory_bytes{app=\"[[app]]\"})"
    }
   ]
  },
  {
   "title": "Open handles",
   "type": "stat",
   "description": "The number of operating system handles the process has opened",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_open_handles{app=~\"[[app]]\"})"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "stat",
   "description": "Returns the number of times garbage collection has occurred for the specified generation of objects",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(dotnet_collection_count_total{app=~\"[[app]]\"}[$interval])) by (generation)",
     "legendFormat": "gen{{generation}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "description": "The availability, internal availability (excludes external dependencies) and service availability (excludes all dependencies)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - sum(rate(http_server_errors_total{app=~\"[[app]]\"}[$interval]) OR on() vector(0))) / \n( \n    sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - \n    sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"invalid_request\"}[$interval]) OR on() vector(0))\n)",
     "legendFormat": "Availability"
    },
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - sum(rate(http_server_errors_total{app=~\"[[app]]\"}[$interval]) OR on() vector(0))) / \n( \n    sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - \n    sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"invalid_request\"}[$interval]) OR on() vector(0)) -           sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"external_dependency\"}[$interval]) OR on() vector(0))\n)",
     "legendFormat": "Internal Availability"
    },
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - sum(rate(http_server_errors_total{app=~\"[[app]]\"}[$interval]) OR on() vector(0))) / \n( \n    sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - \n    sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"invalid_request\"}[$interval]) OR on() vector(0)) -       \n    sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"internal_dependency\"}[$interval]) OR on() vector(0)) -\n    sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"external_dependency\"}[$interval]) OR on() vector(0))\n)",
     "legendFormat": "Service Availability"
    }
   ]
  },
  {
   "title": "Request Rate by Operation",
   "type": "graph",
   "description": "The rate of requests per second per application operation",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[30s])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Request Latency by Operation (99pc)",
   "type": "graph",
   "description": "The 99th percentile request latency by operation",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(http_server_request_duration_seconds_bucket{app=~\"[[app]]\"}[1m])) by (le, operation))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "description": "The total rate of all HTTP requests to the application",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[30s]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "description": "The rate of non-successful status codes across for all HTTP operations",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\", status_code=~\"5..\"}[30s]) OR on() vector(0)) / sum(rate(http_server_request_duration_seconds_count{app=\"[[app]]\"}[30s]))"
    }
   ]
  },
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Request Latency by Percentile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{app=~\"[[app]]\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_request_duration_seconds_bucket{app=~\"[[app]]\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{app=~\"[[app]]\"}[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{app=~\"[[app]]\"}[1m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Status Code Rate",
   "type": "graph",
   "description": "The rate per second that specific HTTP status codes are returned",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Number of requests in progress",
   "type": "graph",
   "description": "The total number of requests in progress",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_in_progress{app=~\"[[app]]\"})"
    }
   ]
  },
  {
   "title": "Error Rate Over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\", status_code=~\"5..\"}[$interval])) / sum(rate(http_server_request_duration_seconds_count{app=\"[[app]]\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Error Rate by Type",
   "type": "graph",
   "description": "The rate of requests that produce errors by error type",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"internal_dependency\"}[$interval]) OR on() vector(0)) / (sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - sum(rate(http_server_errors_total{app=~\"[[app]]\"}[$interval]) OR on() vector(0)))",
     "legendFormat": "Internal Dependency Errors"
    },
    {
     "expr": "sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"external_dependency\"}[$interval]) OR on() vector(0)) / (sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - sum(rate(http_server_errors_total{app=~\"[[app]]\"}[$interval]) OR on() vector(0)))",
     "legendFormat": "External Dependency Errors"
    },
    {
     "expr": "sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"internal\"}[$interval]) OR on() vector(0)) / (sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - sum(rate(http_server_errors_total{app=~\"[[app]]\"}[$interval]) OR on() vector(0)))",
     "legendFormat": "Service Errors"
    },
    {
     "expr": "sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"invalid_request\"}[$interval]) OR on() vector(0)) / (sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - sum(rate(http_server_errors_total{app=~\"[[app]]\"}[$interval]) OR on() vector(0)))",
     "legendFormat": "Invalid Request Errors"
    }
   ]
  },
  {
   "title": "Error Sources",
   "type": "graph",
   "description": "The sources of errors that were caused by dependencies",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_dependency!=\"\"}[$interval])) by (sli_dependency)",
     "legendFormat": "{{sli_dependency}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "graph",
     "description": "The availability of the service inclusive of dependencies",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - sum(rate(http_server_errors_total{app=~\"[[app]]\"}[$interval]) OR on() vector(0))) /\n(\n    sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) \n    - sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"invalid_request\"}[$interval]) OR on() vector(0))\n)",
       "legendFormat": "Service Availability"
      }
     ]
    },
    {
     "title": "Internal Availability",
     "type": "graph",
     "description": "The availability of the service excluding external dependencies",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - sum(rate(http_server_errors_total{app=~\"[[app]]\"}[$interval]) OR on() vector(0))) /\n(\n    sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) \n    - sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"invalid_request\"}[$interval]) OR on() vector(0))\n    - sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"external_dependency\"}[$interval]) OR on() vector(0))\n)",
       "legendFormat": "Service Availability"
      }
     ]
    },
    {
     "title": "Service Availability",
     "type": "graph",
     "description": "The availability of the service excluding any dependencies",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) - sum(rate(http_server_errors_total{app=~\"[[app]]\"}[$interval]) OR on() vector(0))) /\n(\n    sum(rate(http_server_request_duration_seconds_count{app=~\"[[app]]\"}[$interval])) \n    - sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"invalid_request\"}[$interval]) OR on() vector(0))\n    - sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"internal_dependency\"}[$interval]) OR on() vector(0))\n    - sum(rate(http_server_errors_total{app=~\"[[app]]\", sli_error_type=\"external_dependency\"}[$interval]) OR on() vector(0))\n)",
       "legendFormat": "Service Availability"
      }
     ]
    }
   ]
  },
  {
   "title": "CLR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "graph",
     "description": ".NET Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max(dotnet_total_memory_bytes{app=~\"[[app]]\"}) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Num threads",
     "type": "graph",
     "description": "Total number of threads.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(process_num_threads{app=~\"[[app]]\"}) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Open handles",
     "type": "graph",
     "description": "Number of open handles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(process_open_handles{app=~\"[[app]]\"}) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "CPU Seconds",
     "type": "graph",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{app=~\"[[app]]\"}[$interval])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "GC Collections",
     "type": "graph",
     "description": "GC collection count.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rate(dotnet_collection_count_total{app=~\"[[app]]\"}[$interval])) by (generation)",
       "legendFormat": "gen{{generation}}"
      }
     ]
    }
   ]
  }
 ]
}