# my global config
global:
  scrape_interval:     10s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: prometheus

    static_configs:
      - targets: 
        - 'localhost:9090'

  - job_name: aspnet-example

    static_configs:
      - targets: 
        - host.docker.internal:5001
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /metrics